# -*- mode: python ; coding: utf-8 -*-
"""Kenjiri PyInstaller spec — onefile, no console (D26 verbatim:
"PyInstaller --onefile --noconsole").

- Entry: src/kenjiri/__main__.py (T6's entry point; ``--smoke`` supported).
- Data: the committed assets/ audio tree ONLY (assets/music WAV +
  assets/sfx WAV) — D28: committed assets are canonical, the exe bundles
  them as-is and never re-renders (tools/make_assets.py is never imported
  by the app). The window sets no icon from assets at runtime, so
  assets/icon.ico is embedded in the exe resource only, not bundled as data.
- Icon: assets/icon.ico (corgi, generated by tools/make_icon.py).
- Version metadata: v1.0.0 per D23 exe polish, defined inline below.

Build: uv run pyinstaller kenjiri.spec --noconfirm
"""

from PyInstaller.utils.win32.versioninfo import (
    FixedFileInfo,
    StringFileInfo,
    StringStruct,
    StringTable,
    VarFileInfo,
    VarStruct,
    VSVersionInfo,
)

version_info = VSVersionInfo(
    ffi=FixedFileInfo(
        filevers=(1, 0, 0, 0),
        prodvers=(1, 0, 0, 0),
        mask=0x3F,
        flags=0x0,
        OS=0x40004,       # VOS_NT_WINDOWS32
        fileType=0x1,     # VFT_APP
        subtype=0x0,
        date=(0, 0),
    ),
    kids=[
        StringFileInfo(
            [
                StringTable(
                    "040904B0",
                    [
                        StringStruct("CompanyName", ""),
                        StringStruct(
                            "FileDescription",
                            "Kenjiri - a chibi-corgi block puzzle",
                        ),
                        StringStruct("FileVersion", "1.0.0.0"),
                        StringStruct("InternalName", "kenjiri"),
                        StringStruct("LegalCopyright", "Copyright (c) 2026"),
                        StringStruct("OriginalFilename", "kenjiri.exe"),
                        StringStruct("ProductName", "Kenjiri"),
                        StringStruct("ProductVersion", "1.0.0.0"),
                    ],
                )
            ]
        ),
        VarFileInfo([VarStruct("Translation", [1033, 1200])]),
    ],
)

a = Analysis(
    ["src/kenjiri/__main__.py"],
    pathex=["src"],
    binaries=[],
    datas=[
        ("assets/music", "assets/music"),
        ("assets/sfx", "assets/sfx"),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="kenjiri",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,          # --noconsole (D26)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="assets/icon.ico",
    version=version_info,   # v1.0.0 metadata (D23)
)
