# -*- mode: python ; coding: utf-8 -*-
"""Kenjiri macOS PyInstaller spec — onefile executable wrapped in a .app
BUNDLE (D26 packaging posture, macOS sibling of ``kenjiri.spec``).

This is a **platform addition, not a version-up** — v1.0.0 stays v1.0.0.
It mirrors ``kenjiri.spec`` exactly for Analysis/data bundling and differs
only where the platform requires:

- **No Windows ``VSVersionInfo`` resource.** That block (and its
  ``PyInstaller.utils.win32`` import) is Windows-only; the mac version string
  lives in the bundle's ``Info.plist`` (``CFBundleShortVersionString``).
- **``console=False``** — windowed app, no terminal (matches ``--noconsole``).
- **``BUNDLE``** wraps the EXE into ``Kenjiri.app`` with the ``.icns`` icon and
  a minimal ``Info.plist``.

- Entry: src/kenjiri/__main__.py (``--smoke`` supported; the smoke check runs
  ``dist/Kenjiri.app/Contents/MacOS/kenjiri --smoke``).
- Data: the committed assets/ audio tree ONLY (assets/music WAV +
  assets/sfx WAV) — D28: committed assets are canonical, bundled as-is,
  never re-rendered at runtime.
- Icon: assets/icon.icns (corgi, generated by ``tools/make_icon.py --icns``).

Build: uv run pyinstaller kenjiri-mac.spec --noconfirm
"""

a = Analysis(
    ["src/kenjiri/__main__.py"],
    pathex=["src"],
    binaries=[],
    datas=[
        ("assets/music", "assets/music"),
        ("assets/sfx", "assets/sfx"),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="kenjiri",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,          # windowed app, no terminal (D26)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="assets/icon.icns",
)

app = BUNDLE(
    exe,
    name="Kenjiri.app",
    icon="assets/icon.icns",
    bundle_identifier="ai.kataharness.kenjiri",
    info_plist={
        "CFBundleShortVersionString": "1.0.0",
        "NSHighResolutionCapable": True,
    },
)
